// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: d8c17cf0002df517b012d54cccebaed5310d085a2d480878c613d55c7ec5755b
// Version: v1.1.0 (https://github.com/pk910/dynamic-ssz)
package main

import (
	"github.com/attestantio/go-eth2-client/spec/altair"
	"github.com/attestantio/go-eth2-client/spec/capella"
	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
	go_bitfield "github.com/prysmaticlabs/go-bitfield"
)

var _ = sszutils.ErrListTooBig

func (t *TestBeaconState) MarshalSSZDyn(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(TestBeaconState)
	}
	dstlen := len(dst)
	{ // Field #0 'GenesisTime'
		t := t.GenesisTime
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #1 'GenesisValidatorsRoot'
		t := t.GenesisValidatorsRoot
		dst = append(dst, []byte(t[:32])...)
	}
	{ // Field #2 'Slot'
		t := t.Slot
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #5 'BlockRoots'
		t := t.BlockRoots
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return dst, err
		}
		if !hasLimit {
			limit = 8192
		}
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrVectorLength
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = append(dst, []byte(t[:32])...)
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*32)
		}
	}
	{ // Field #6 'StateRoots'
		t := t.StateRoots
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return dst, err
		}
		if !hasLimit {
			limit = 8192
		}
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrVectorLength
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = append(dst, []byte(t[:32])...)
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*32)
		}
	}
	// Offset #7 'HistoricalRoots'
	offset7 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #8 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	// Offset #9 'ETH1DataVotes'
	offset9 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #10 'ETH1DepositIndex'
		t := t.ETH1DepositIndex
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	// Offset #11 'Validators'
	offset11 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	// Offset #12 'Balances'
	offset12 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_HISTORICAL_VECTOR")
		if err != nil {
			return dst, err
		}
		if !hasLimit {
			limit = 65536
		}
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrVectorLength
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = append(dst, []byte(t[:32])...)
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*32)
		}
	}
	{ // Field #14 'Slashings'
		t := t.Slashings
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_SLASHINGS_VECTOR")
		if err != nil {
			return dst, err
		}
		if !hasLimit {
			limit = 8192
		}
		vlen := len(t)
		if vlen > int(limit) {
			return dst, sszutils.ErrVectorLength
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint64(dst, uint64(t))
		}
		if vlen < int(limit) {
			dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*8)
		}
	}
	// Offset #15 'PreviousEpochParticipation'
	offset15 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	// Offset #16 'CurrentEpochParticipation'
	offset16 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #17 'JustificationBits'
		t := t.JustificationBits
		vlen := len(t)
		if vlen > 1 {
			return dst, sszutils.ErrVectorLength
		}
		dst = append(dst, []byte(t[:vlen])...)
		if vlen < 1 {
			dst = sszutils.AppendZeroPadding(dst, (1-vlen)*1)
		}
	}
	{ // Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	// Offset #21 'InactivityScores'
	offset21 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		{ // Field #0 'Pubkeys'
			t := t.Pubkeys
			hasLimit, limit, err := ds.ResolveSpecValue("SYNC_COMMITTEE_SIZE")
			if err != nil {
				return dst, err
			}
			if !hasLimit {
				limit = 512
			}
			vlen := len(t)
			if vlen > int(limit) {
				return dst, sszutils.ErrVectorLength
			}
			for i := 0; i < vlen; i++ {
				t := t[i]
				dst = append(dst, []byte(t[:48])...)
			}
			if vlen < int(limit) {
				dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*48)
			}
		}
		{ // Field #1 'AggregatePubkey'
			t := t.AggregatePubkey
			dst = append(dst, []byte(t[:48])...)
		}
	}
	{ // Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		{ // Field #0 'Pubkeys'
			t := t.Pubkeys
			hasLimit, limit, err := ds.ResolveSpecValue("SYNC_COMMITTEE_SIZE")
			if err != nil {
				return dst, err
			}
			if !hasLimit {
				limit = 512
			}
			vlen := len(t)
			if vlen > int(limit) {
				return dst, sszutils.ErrVectorLength
			}
			for i := 0; i < vlen; i++ {
				t := t[i]
				dst = append(dst, []byte(t[:48])...)
			}
			if vlen < int(limit) {
				dst = sszutils.AppendZeroPadding(dst, (int(limit)-vlen)*48)
			}
		}
		{ // Field #1 'AggregatePubkey'
			t := t.AggregatePubkey
			dst = append(dst, []byte(t[:48])...)
		}
	}
	// Offset #24 'LatestExecutionPayloadHeader'
	offset24 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Field #25 'NextWithdrawalIndex'
		t := t.NextWithdrawalIndex
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex'
		t := t.NextWithdrawalValidatorIndex
		dst = sszutils.MarshalUint64(dst, uint64(t))
	}
	// Offset #27 'HistoricalSummaries'
	offset27 := len(dst)
	dst = sszutils.MarshalOffset(dst, 0)
	{ // Dynamic Field #7 'HistoricalRoots'
		sszutils.UpdateOffset(dst[offset7:offset7+4], len(dst)-dstlen)
		t := t.HistoricalRoots
		hasMax, max, err := ds.ResolveSpecValue("HISTORICAL_ROOTS_LIMIT")
		if err != nil {
			return dst, err
		}
		if !hasMax {
			max = 16777216
		}
		vlen := len(t)
		if vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = append(dst, []byte(t[:32])...)
		}
	}
	{ // Dynamic Field #9 'ETH1DataVotes'
		sszutils.UpdateOffset(dst[offset9:offset9+4], len(dst)-dstlen)
		t := t.ETH1DataVotes
		hasMax, max, err := ds.ResolveSpecValue("EPOCHS_PER_ETH1_VOTING_PERIOD*SLOTS_PER_EPOCH")
		if err != nil {
			return dst, err
		}
		if !hasMax {
			max = 2048
		}
		vlen := len(t)
		if vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if t == nil {
				t = new(phase0.ETH1Data)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	{ // Dynamic Field #11 'Validators'
		sszutils.UpdateOffset(dst[offset11:offset11+4], len(dst)-dstlen)
		t := t.Validators
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return dst, err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := len(t)
		if vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if t == nil {
				t = new(phase0.Validator)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	{ // Dynamic Field #12 'Balances'
		sszutils.UpdateOffset(dst[offset12:offset12+4], len(dst)-dstlen)
		t := t.Balances
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return dst, err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := len(t)
		if vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint64(dst, uint64(t))
		}
	}
	{ // Dynamic Field #15 'PreviousEpochParticipation'
		sszutils.UpdateOffset(dst[offset15:offset15+4], len(dst)-dstlen)
		t := t.PreviousEpochParticipation
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return dst, err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := len(t)
		if vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint8(dst, uint8(t))
		}
	}
	{ // Dynamic Field #16 'CurrentEpochParticipation'
		sszutils.UpdateOffset(dst[offset16:offset16+4], len(dst)-dstlen)
		t := t.CurrentEpochParticipation
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return dst, err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := len(t)
		if vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint8(dst, uint8(t))
		}
	}
	{ // Dynamic Field #21 'InactivityScores'
		sszutils.UpdateOffset(dst[offset21:offset21+4], len(dst)-dstlen)
		t := t.InactivityScores
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return dst, err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := len(t)
		if vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			dst = sszutils.MarshalUint64(dst, uint64(t))
		}
	}
	{ // Dynamic Field #24 'LatestExecutionPayloadHeader'
		sszutils.UpdateOffset(dst[offset24:offset24+4], len(dst)-dstlen)
		t := t.LatestExecutionPayloadHeader
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return dst, err
		}
	}
	{ // Dynamic Field #27 'HistoricalSummaries'
		sszutils.UpdateOffset(dst[offset27:offset27+4], len(dst)-dstlen)
		t := t.HistoricalSummaries
		hasMax, max, err := ds.ResolveSpecValue("HISTORICAL_ROOTS_LIMIT")
		if err != nil {
			return dst, err
		}
		if !hasMax {
			max = 16777216
		}
		vlen := len(t)
		if vlen > int(max) {
			return dst, sszutils.ErrListTooBig
		}
		for i := 0; i < vlen; i++ {
			t := t[i]
			if t == nil {
				t = new(capella.HistoricalSummary)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return dst, err
			}
		}
	}
	return dst, nil
}

func (t *TestBeaconState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	return t.MarshalSSZDyn(dynssz.GetGlobalDynSsz(), buf)
}

func (t *TestBeaconState) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *TestBeaconState) SizeSSZDyn(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(TestBeaconState)
	}
	// Field #0 'GenesisTime' static (8 bytes)
	// Field #1 'GenesisValidatorsRoot' static (32 bytes)
	// Field #2 'Slot' static (8 bytes)
	// Field #3 'Fork' static (16 bytes)
	// Field #4 'LatestBlockHeader' static (112 bytes)
	// Field #7 'HistoricalRoots' offset (4 bytes)
	// Field #8 'ETH1Data' static (72 bytes)
	// Field #9 'ETH1DataVotes' offset (4 bytes)
	// Field #10 'ETH1DepositIndex' static (8 bytes)
	// Field #11 'Validators' offset (4 bytes)
	// Field #12 'Balances' offset (4 bytes)
	// Field #15 'PreviousEpochParticipation' offset (4 bytes)
	// Field #16 'CurrentEpochParticipation' offset (4 bytes)
	// Field #17 'JustificationBits' static (1 bytes)
	// Field #18 'PreviousJustifiedCheckpoint' static (40 bytes)
	// Field #19 'CurrentJustifiedCheckpoint' static (40 bytes)
	// Field #20 'FinalizedCheckpoint' static (40 bytes)
	// Field #21 'InactivityScores' offset (4 bytes)
	// Field #24 'LatestExecutionPayloadHeader' offset (4 bytes)
	// Field #25 'NextWithdrawalIndex' static (8 bytes)
	// Field #26 'NextWithdrawalValidatorIndex' static (8 bytes)
	// Field #27 'HistoricalSummaries' offset (4 bytes)
	size += 429
	{ // Field #5 'BlockRoots'
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return 0
		}
		if !hasLimit {
			limit = 8192
		}
		size += int(limit) * 32
	}
	{ // Field #6 'StateRoots'
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return 0
		}
		if !hasLimit {
			limit = 8192
		}
		size += int(limit) * 32
	}
	{ // Field #13 'RANDAOMixes'
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_HISTORICAL_VECTOR")
		if err != nil {
			return 0
		}
		if !hasLimit {
			limit = 65536
		}
		size += int(limit) * 32
	}
	{ // Field #14 'Slashings'
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_SLASHINGS_VECTOR")
		if err != nil {
			return 0
		}
		if !hasLimit {
			limit = 8192
		}
		size += int(limit) * 8
	}
	{ // Field #22 'CurrentSyncCommittee'
		if t.CurrentSyncCommittee == nil {
			t.CurrentSyncCommittee = new(altair.SyncCommittee)
		}
		size += t.CurrentSyncCommittee.SizeSSZ()
	}
	{ // Field #23 'NextSyncCommittee'
		if t.NextSyncCommittee == nil {
			t.NextSyncCommittee = new(altair.SyncCommittee)
		}
		size += t.NextSyncCommittee.SizeSSZ()
	}
	{ // Dynamic field #7 'HistoricalRoots'
		vlen := len(t.HistoricalRoots)
		size += vlen * 32
	}
	{ // Dynamic field #9 'ETH1DataVotes'
		vlen := len(t.ETH1DataVotes)
		size += vlen * 72
	}
	{ // Dynamic field #11 'Validators'
		vlen := len(t.Validators)
		size += vlen * 121
	}
	{ // Dynamic field #12 'Balances'
		vlen := len(t.Balances)
		size += vlen * 8
	}
	{ // Dynamic field #15 'PreviousEpochParticipation'
		vlen := len(t.PreviousEpochParticipation)
		size += vlen * 1
	}
	{ // Dynamic field #16 'CurrentEpochParticipation'
		vlen := len(t.CurrentEpochParticipation)
		size += vlen * 1
	}
	{ // Dynamic field #21 'InactivityScores'
		vlen := len(t.InactivityScores)
		size += vlen * 8
	}
	{ // Dynamic field #24 'LatestExecutionPayloadHeader'
		if t.LatestExecutionPayloadHeader == nil {
			t.LatestExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
		}
		size += t.LatestExecutionPayloadHeader.SizeSSZ()
	}
	{ // Dynamic field #27 'HistoricalSummaries'
		vlen := len(t.HistoricalSummaries)
		size += vlen * 64
	}
	return size
}

func (t *TestBeaconState) SizeSSZ() (size int) {
	return t.SizeSSZDyn(dynssz.GetGlobalDynSsz())
}

func (t *TestBeaconState) UnmarshalSSZDyn(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	size1 := 32 // size expression for '[]Root'
	{
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		size1 = size1 * int(limit)
	}
	size2 := 32 // size expression for '[]Root'
	{
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		size2 = size2 * int(limit)
	}
	size3 := 32 // size expression for '[]Root'
	{
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_HISTORICAL_VECTOR")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 65536
		}
		size3 = size3 * int(limit)
	}
	size4 := 8 // size expression for '[]Gwei'
	{
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_SLASHINGS_VECTOR")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		size4 = size4 * int(limit)
	}
	size6 := 48 // size expression for '[]BLSPubKey'
	{
		hasLimit, limit, err := ds.ResolveSpecValue("SYNC_COMMITTEE_SIZE")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 512
		}
		size6 = size6 * int(limit)
	}
	size5 := size6+48 // size expression for '*SyncCommittee'
	exproffset := 0
	buflen := len(buf)
	if buflen < size1+size2+size3+size4+size5+size5+429 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'GenesisTime' (static)
		buf := buf[0:8]
		t.GenesisTime = uint64(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #1 'GenesisValidatorsRoot' (static)
		buf := buf[8:40]
		copy(t.GenesisValidatorsRoot[:], buf)
	}
	{ // Field #2 'Slot' (static)
		buf := buf[40:48]
		t.Slot = phase0.Slot(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #3 'Fork' (static)
		buf := buf[48:64]
		if t.Fork == nil {
			t.Fork = new(phase0.Fork)
		}
		if err = t.Fork.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #4 'LatestBlockHeader' (static)
		buf := buf[64:176]
		if t.LatestBlockHeader == nil {
			t.LatestBlockHeader = new(phase0.BeaconBlockHeader)
		}
		if err = t.LatestBlockHeader.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #5 'BlockRoots' (static)
		buf := buf[176 : size1+176]
		exproffset += int(size1)
		val1 := t.BlockRoots
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		if len(val1) < int(limit) {
			val1 = make([]phase0.Root, int(limit))
		} else if len(val1) > int(limit) {
			val1 = val1[:int(limit)]
		}
		for i := 0; i < int(limit); i++ {
			buf := buf[32*i : 32*(i+1)]
			copy(val1[i][:], buf)
		}
		t.BlockRoots = val1
	}
	{ // Field #6 'StateRoots' (static)
		buf := buf[exproffset+176 : exproffset+size2+176]
		exproffset += int(size2)
		val2 := t.StateRoots
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		if len(val2) < int(limit) {
			val2 = make([]phase0.Root, int(limit))
		} else if len(val2) > int(limit) {
			val2 = val2[:int(limit)]
		}
		for i := 0; i < int(limit); i++ {
			buf := buf[32*i : 32*(i+1)]
			copy(val2[i][:], buf)
		}
		t.StateRoots = val2
	}
	// Field #7 'HistoricalRoots' (offset)
	offset7 := int(sszutils.UnmarshallUint32(buf[exproffset+176 : exproffset+180]))
	if offset7 < size1+size2+size3+size4+size5+size5+429 || offset7 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #8 'ETH1Data' (static)
		buf := buf[exproffset+180 : exproffset+252]
		if t.ETH1Data == nil {
			t.ETH1Data = new(phase0.ETH1Data)
		}
		if err = t.ETH1Data.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	// Field #9 'ETH1DataVotes' (offset)
	offset9 := int(sszutils.UnmarshallUint32(buf[exproffset+252 : exproffset+256]))
	if offset9 < offset7 || offset9 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #10 'ETH1DepositIndex' (static)
		buf := buf[exproffset+256 : exproffset+264]
		t.ETH1DepositIndex = uint64(sszutils.UnmarshallUint64(buf))
	}
	// Field #11 'Validators' (offset)
	offset11 := int(sszutils.UnmarshallUint32(buf[exproffset+264 : exproffset+268]))
	if offset11 < offset9 || offset11 > buflen {
		return sszutils.ErrOffset
	}
	// Field #12 'Balances' (offset)
	offset12 := int(sszutils.UnmarshallUint32(buf[exproffset+268 : exproffset+272]))
	if offset12 < offset11 || offset12 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #13 'RANDAOMixes' (static)
		buf := buf[exproffset+272 : exproffset+size3+272]
		exproffset += int(size3)
		val3 := t.RANDAOMixes
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_HISTORICAL_VECTOR")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 65536
		}
		if len(val3) < int(limit) {
			val3 = make([]phase0.Root, int(limit))
		} else if len(val3) > int(limit) {
			val3 = val3[:int(limit)]
		}
		for i := 0; i < int(limit); i++ {
			buf := buf[32*i : 32*(i+1)]
			copy(val3[i][:], buf)
		}
		t.RANDAOMixes = val3
	}
	{ // Field #14 'Slashings' (static)
		buf := buf[exproffset+272 : exproffset+size4+272]
		exproffset += int(size4)
		val4 := t.Slashings
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_SLASHINGS_VECTOR")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		if len(val4) < int(limit) {
			val4 = make([]phase0.Gwei, int(limit))
		} else if len(val4) > int(limit) {
			val4 = val4[:int(limit)]
		}
		for i := 0; i < int(limit); i++ {
			buf := buf[8*i : 8*(i+1)]
			val4[i] = phase0.Gwei(sszutils.UnmarshallUint64(buf))
		}
		t.Slashings = val4
	}
	// Field #15 'PreviousEpochParticipation' (offset)
	offset15 := int(sszutils.UnmarshallUint32(buf[exproffset+272 : exproffset+276]))
	if offset15 < offset12 || offset15 > buflen {
		return sszutils.ErrOffset
	}
	// Field #16 'CurrentEpochParticipation' (offset)
	offset16 := int(sszutils.UnmarshallUint32(buf[exproffset+276 : exproffset+280]))
	if offset16 < offset15 || offset16 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #17 'JustificationBits' (static)
		buf := buf[exproffset+280 : exproffset+281]
		if len(t.JustificationBits) < 1 {
			t.JustificationBits = make(go_bitfield.Bitvector4, 1)
		} else if len(t.JustificationBits) > 1 {
			t.JustificationBits = t.JustificationBits[:1]
		}
		copy(t.JustificationBits[:], buf)
	}
	{ // Field #18 'PreviousJustifiedCheckpoint' (static)
		buf := buf[exproffset+281 : exproffset+321]
		if t.PreviousJustifiedCheckpoint == nil {
			t.PreviousJustifiedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.PreviousJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint' (static)
		buf := buf[exproffset+321 : exproffset+361]
		if t.CurrentJustifiedCheckpoint == nil {
			t.CurrentJustifiedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.CurrentJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #20 'FinalizedCheckpoint' (static)
		buf := buf[exproffset+361 : exproffset+401]
		if t.FinalizedCheckpoint == nil {
			t.FinalizedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.FinalizedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	// Field #21 'InactivityScores' (offset)
	offset21 := int(sszutils.UnmarshallUint32(buf[exproffset+401 : exproffset+405]))
	if offset21 < offset16 || offset21 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #22 'CurrentSyncCommittee' (static)
		buf := buf[exproffset+405 : exproffset+size5+405]
		exproffset += int(size5)
		val5 := t.CurrentSyncCommittee
		if val5 == nil {
			val5 = new(altair.SyncCommittee)
		}
		exproffset := 0
		buflen := len(buf)
		if buflen < size6+48 {
			return sszutils.ErrUnexpectedEOF
		}
		{ // Field #0 'Pubkeys' (static)
			buf := buf[0 : size6+0]
			exproffset += int(size6)
			val6 := val5.Pubkeys
			hasLimit, limit, err := ds.ResolveSpecValue("SYNC_COMMITTEE_SIZE")
			if err != nil {
				return err
			}
			if !hasLimit {
				limit = 512
			}
			if len(val6) < int(limit) {
				val6 = make([]phase0.BLSPubKey, int(limit))
			} else if len(val6) > int(limit) {
				val6 = val6[:int(limit)]
			}
			for i := 0; i < int(limit); i++ {
				buf := buf[48*i : 48*(i+1)]
				copy(val6[i][:], buf)
			}
			val5.Pubkeys = val6
		}
		{ // Field #1 'AggregatePubkey' (static)
			buf := buf[exproffset+0 : exproffset+48]
			copy(val5.AggregatePubkey[:], buf)
		}
		t.CurrentSyncCommittee = val5
	}
	{ // Field #23 'NextSyncCommittee' (static)
		buf := buf[exproffset+405 : exproffset+size5+405]
		exproffset += int(size5)
		val7 := t.NextSyncCommittee
		if val7 == nil {
			val7 = new(altair.SyncCommittee)
		}
		exproffset := 0
		buflen := len(buf)
		if buflen < size6+48 {
			return sszutils.ErrUnexpectedEOF
		}
		{ // Field #0 'Pubkeys' (static)
			buf := buf[0 : size6+0]
			exproffset += int(size6)
			val8 := val7.Pubkeys
			hasLimit, limit, err := ds.ResolveSpecValue("SYNC_COMMITTEE_SIZE")
			if err != nil {
				return err
			}
			if !hasLimit {
				limit = 512
			}
			if len(val8) < int(limit) {
				val8 = make([]phase0.BLSPubKey, int(limit))
			} else if len(val8) > int(limit) {
				val8 = val8[:int(limit)]
			}
			for i := 0; i < int(limit); i++ {
				buf := buf[48*i : 48*(i+1)]
				copy(val8[i][:], buf)
			}
			val7.Pubkeys = val8
		}
		{ // Field #1 'AggregatePubkey' (static)
			buf := buf[exproffset+0 : exproffset+48]
			copy(val7.AggregatePubkey[:], buf)
		}
		t.NextSyncCommittee = val7
	}
	// Field #24 'LatestExecutionPayloadHeader' (offset)
	offset24 := int(sszutils.UnmarshallUint32(buf[exproffset+405 : exproffset+409]))
	if offset24 < offset21 || offset24 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #25 'NextWithdrawalIndex' (static)
		buf := buf[exproffset+409 : exproffset+417]
		t.NextWithdrawalIndex = capella.WithdrawalIndex(sszutils.UnmarshallUint64(buf))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex' (static)
		buf := buf[exproffset+417 : exproffset+425]
		t.NextWithdrawalValidatorIndex = phase0.ValidatorIndex(sszutils.UnmarshallUint64(buf))
	}
	// Field #27 'HistoricalSummaries' (offset)
	offset27 := int(sszutils.UnmarshallUint32(buf[exproffset+425 : exproffset+429]))
	if offset27 < offset24 || offset27 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #7 'HistoricalRoots' (dynamic)
		buf := buf[offset7:offset9]
		val9 := t.HistoricalRoots
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if len(val9) < itemCount {
			val9 = make([]phase0.Root, itemCount)
		} else if len(val9) > itemCount {
			val9 = val9[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[32*i : 32*(i+1)]
			copy(val9[i][:], buf)
		}
		t.HistoricalRoots = val9
	}
	{ // Field #9 'ETH1DataVotes' (dynamic)
		buf := buf[offset9:offset11]
		val10 := t.ETH1DataVotes
		itemCount := len(buf) / 72
		if len(buf)%72 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if len(val10) < itemCount {
			val10 = make([]*phase0.ETH1Data, itemCount)
		} else if len(val10) > itemCount {
			val10 = val10[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			if val10[i] == nil {
				val10[i] = new(phase0.ETH1Data)
			}
			buf := buf[72*i : 72*(i+1)]
			if err = val10[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.ETH1DataVotes = val10
	}
	{ // Field #11 'Validators' (dynamic)
		buf := buf[offset11:offset12]
		val11 := t.Validators
		itemCount := len(buf) / 121
		if len(buf)%121 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if len(val11) < itemCount {
			val11 = make([]*phase0.Validator, itemCount)
		} else if len(val11) > itemCount {
			val11 = val11[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			if val11[i] == nil {
				val11[i] = new(phase0.Validator)
			}
			buf := buf[121*i : 121*(i+1)]
			if err = val11[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.Validators = val11
	}
	{ // Field #12 'Balances' (dynamic)
		buf := buf[offset12:offset15]
		val12 := t.Balances
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if len(val12) < itemCount {
			val12 = make([]phase0.Gwei, itemCount)
		} else if len(val12) > itemCount {
			val12 = val12[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[8*i : 8*(i+1)]
			val12[i] = phase0.Gwei(sszutils.UnmarshallUint64(buf))
		}
		t.Balances = val12
	}
	{ // Field #15 'PreviousEpochParticipation' (dynamic)
		buf := buf[offset15:offset16]
		val13 := t.PreviousEpochParticipation
		itemCount := len(buf)
		if len(val13) < itemCount {
			val13 = make([]altair.ParticipationFlags, itemCount)
		} else if len(val13) > itemCount {
			val13 = val13[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[1*i : 1*(i+1)]
			val13[i] = altair.ParticipationFlags(sszutils.UnmarshallUint8(buf))
		}
		t.PreviousEpochParticipation = val13
	}
	{ // Field #16 'CurrentEpochParticipation' (dynamic)
		buf := buf[offset16:offset21]
		val14 := t.CurrentEpochParticipation
		itemCount := len(buf)
		if len(val14) < itemCount {
			val14 = make([]altair.ParticipationFlags, itemCount)
		} else if len(val14) > itemCount {
			val14 = val14[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[1*i : 1*(i+1)]
			val14[i] = altair.ParticipationFlags(sszutils.UnmarshallUint8(buf))
		}
		t.CurrentEpochParticipation = val14
	}
	{ // Field #21 'InactivityScores' (dynamic)
		buf := buf[offset21:offset24]
		val15 := t.InactivityScores
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if len(val15) < itemCount {
			val15 = make([]uint64, itemCount)
		} else if len(val15) > itemCount {
			val15 = val15[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			buf := buf[8*i : 8*(i+1)]
			val15[i] = uint64(sszutils.UnmarshallUint64(buf))
		}
		t.InactivityScores = val15
	}
	{ // Field #24 'LatestExecutionPayloadHeader' (dynamic)
		buf := buf[offset24:offset27]
		val16 := t.LatestExecutionPayloadHeader
		if val16 == nil {
			val16 = new(deneb.ExecutionPayloadHeader)
		}
		if err = val16.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.LatestExecutionPayloadHeader = val16
	}
	{ // Field #27 'HistoricalSummaries' (dynamic)
		buf := buf[offset27:]
		val17 := t.HistoricalSummaries
		itemCount := len(buf) / 64
		if len(buf)%64 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		if len(val17) < itemCount {
			val17 = make([]*capella.HistoricalSummary, itemCount)
		} else if len(val17) > itemCount {
			val17 = val17[:itemCount]
		}
		for i := 0; i < itemCount; i++ {
			if val17[i] == nil {
				val17[i] = new(capella.HistoricalSummary)
			}
			buf := buf[64*i : 64*(i+1)]
			if err = val17[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.HistoricalSummaries = val17
	}
	return nil
}

func (t *TestBeaconState) UnmarshalSSZ(buf []byte) (err error) {
	return t.UnmarshalSSZDyn(dynssz.GetGlobalDynSsz(), buf)
}

func (t *TestBeaconState) HashTreeRootWithDyn(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(TestBeaconState)
	}
	idx := hh.Index()
	{ // Field #0 'GenesisTime'
		t := t.GenesisTime
		hh.PutUint64(uint64(t))
	}
	{ // Field #1 'GenesisValidatorsRoot'
		t := t.GenesisValidatorsRoot
		hh.PutBytes(t[:32])
	}
	{ // Field #2 'Slot'
		t := t.Slot
		hh.PutUint64(uint64(t))
	}
	{ // Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #5 'BlockRoots'
		t := t.BlockRoots
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrVectorLength
		}
		idx := hh.Index()
		for i := 0; i < int(limit); i++ {
			var val1 phase0.Root
			if i < vlen {
				val1 = t[i]
			}
			hh.PutBytes(val1[:32])
		}
		hh.Merkleize(idx)
	}
	{ // Field #6 'StateRoots'
		t := t.StateRoots
		hasLimit, limit, err := ds.ResolveSpecValue("SLOTS_PER_HISTORICAL_ROOT")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrVectorLength
		}
		idx := hh.Index()
		for i := 0; i < int(limit); i++ {
			var val2 phase0.Root
			if i < vlen {
				val2 = t[i]
			}
			hh.PutBytes(val2[:32])
		}
		hh.Merkleize(idx)
	}
	{ // Field #7 'HistoricalRoots'
		t := t.HistoricalRoots
		hasMax, max, err := ds.ResolveSpecValue("HISTORICAL_ROOTS_LIMIT")
		if err != nil {
			return err
		}
		if !hasMax {
			max = 16777216
		}
		vlen := uint64(len(t))
		if vlen > uint64(max) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.PutBytes(t[:32])
		}
		limit := sszutils.CalculateLimit(uint64(max), vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #8 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #9 'ETH1DataVotes'
		t := t.ETH1DataVotes
		hasMax, max, err := ds.ResolveSpecValue("EPOCHS_PER_ETH1_VOTING_PERIOD*SLOTS_PER_EPOCH")
		if err != nil {
			return err
		}
		if !hasMax {
			max = 2048
		}
		vlen := uint64(len(t))
		if vlen > uint64(max) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if t == nil {
				t = new(phase0.ETH1Data)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(uint64(max), vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #10 'ETH1DepositIndex'
		t := t.ETH1DepositIndex
		hh.PutUint64(uint64(t))
	}
	{ // Field #11 'Validators'
		t := t.Validators
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := uint64(len(t))
		if vlen > uint64(max) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if t == nil {
				t = new(phase0.Validator)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(uint64(max), vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #12 'Balances'
		t := t.Balances
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := uint64(len(t))
		if vlen > uint64(max) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint64(uint64(t))
		}
		hh.FillUpTo32()
		limit := sszutils.CalculateLimit(uint64(max), vlen, 8)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_HISTORICAL_VECTOR")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 65536
		}
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrVectorLength
		}
		idx := hh.Index()
		for i := 0; i < int(limit); i++ {
			var val3 phase0.Root
			if i < vlen {
				val3 = t[i]
			}
			hh.PutBytes(val3[:32])
		}
		hh.Merkleize(idx)
	}
	{ // Field #14 'Slashings'
		t := t.Slashings
		hasLimit, limit, err := ds.ResolveSpecValue("EPOCHS_PER_SLASHINGS_VECTOR")
		if err != nil {
			return err
		}
		if !hasLimit {
			limit = 8192
		}
		vlen := len(t)
		if vlen > int(limit) {
			return sszutils.ErrVectorLength
		}
		idx := hh.Index()
		for i := 0; i < int(limit); i++ {
			var val4 phase0.Gwei
			if i < vlen {
				val4 = t[i]
			}
			hh.AppendUint64(uint64(val4))
		}
		hh.FillUpTo32()
		hh.Merkleize(idx)
	}
	{ // Field #15 'PreviousEpochParticipation'
		t := t.PreviousEpochParticipation
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := uint64(len(t))
		if vlen > uint64(max) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint8(uint8(t))
		}
		hh.FillUpTo32()
		limit := sszutils.CalculateLimit(uint64(max), vlen, 1)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #16 'CurrentEpochParticipation'
		t := t.CurrentEpochParticipation
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := uint64(len(t))
		if vlen > uint64(max) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint8(uint8(t))
		}
		hh.FillUpTo32()
		limit := sszutils.CalculateLimit(uint64(max), vlen, 1)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #17 'JustificationBits'
		t := t.JustificationBits
		vlen := len(t)
		if vlen > 1 {
			return sszutils.ErrVectorLength
		}
		val := t[:]
		if vlen < 1 {
			val = sszutils.AppendZeroPadding(val, (1-vlen)*1)
		}
		hh.PutBytes(val[:1])
	}
	{ // Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #21 'InactivityScores'
		t := t.InactivityScores
		hasMax, max, err := ds.ResolveSpecValue("VALIDATOR_REGISTRY_LIMIT")
		if err != nil {
			return err
		}
		if !hasMax {
			max = 1099511627776
		}
		vlen := uint64(len(t))
		if vlen > uint64(max) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			hh.AppendUint64(uint64(t))
		}
		hh.FillUpTo32()
		limit := sszutils.CalculateLimit(uint64(max), vlen, 8)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	{ // Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		idx := hh.Index()
		{ // Field #0 'Pubkeys'
			t := t.Pubkeys
			hasLimit, limit, err := ds.ResolveSpecValue("SYNC_COMMITTEE_SIZE")
			if err != nil {
				return err
			}
			if !hasLimit {
				limit = 512
			}
			vlen := len(t)
			if vlen > int(limit) {
				return sszutils.ErrVectorLength
			}
			idx := hh.Index()
			for i := 0; i < int(limit); i++ {
				var val5 phase0.BLSPubKey
				if i < vlen {
					val5 = t[i]
				}
				hh.PutBytes(val5[:48])
			}
			hh.Merkleize(idx)
		}
		{ // Field #1 'AggregatePubkey'
			t := t.AggregatePubkey
			hh.PutBytes(t[:48])
		}
		hh.Merkleize(idx)
	}
	{ // Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		idx := hh.Index()
		{ // Field #0 'Pubkeys'
			t := t.Pubkeys
			hasLimit, limit, err := ds.ResolveSpecValue("SYNC_COMMITTEE_SIZE")
			if err != nil {
				return err
			}
			if !hasLimit {
				limit = 512
			}
			vlen := len(t)
			if vlen > int(limit) {
				return sszutils.ErrVectorLength
			}
			idx := hh.Index()
			for i := 0; i < int(limit); i++ {
				var val6 phase0.BLSPubKey
				if i < vlen {
					val6 = t[i]
				}
				hh.PutBytes(val6[:48])
			}
			hh.Merkleize(idx)
		}
		{ // Field #1 'AggregatePubkey'
			t := t.AggregatePubkey
			hh.PutBytes(t[:48])
		}
		hh.Merkleize(idx)
	}
	{ // Field #24 'LatestExecutionPayloadHeader'
		t := t.LatestExecutionPayloadHeader
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #25 'NextWithdrawalIndex'
		t := t.NextWithdrawalIndex
		hh.PutUint64(uint64(t))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex'
		t := t.NextWithdrawalValidatorIndex
		hh.PutUint64(uint64(t))
	}
	{ // Field #27 'HistoricalSummaries'
		t := t.HistoricalSummaries
		hasMax, max, err := ds.ResolveSpecValue("HISTORICAL_ROOTS_LIMIT")
		if err != nil {
			return err
		}
		if !hasMax {
			max = 16777216
		}
		vlen := uint64(len(t))
		if vlen > uint64(max) {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := 0; i < int(vlen); i++ {
			t := t[i]
			if t == nil {
				t = new(capella.HistoricalSummary)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		limit := sszutils.CalculateLimit(uint64(max), vlen, 32)
		hh.MerkleizeWithMixin(idx, vlen, limit)
	}
	hh.Merkleize(idx)
	return nil
}

func (t *TestBeaconState) HashTreeRootWith(hh sszutils.HashWalker) error {
	return t.HashTreeRootWithDyn(dynssz.GetGlobalDynSsz(), hh)
}

func (t *TestBeaconState) HashTreeRootDyn(ds sszutils.DynamicSpecs) ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWithDyn(ds, hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}

func (t *TestBeaconState) HashTreeRoot() ([32]byte, error) {
	pool := &hasher.FastHasherPool
	hh := pool.Get()
	defer func() {
		pool.Put(hh)
	}()
	if err := t.HashTreeRootWith(hh); err != nil {
		return [32]byte{}, err
	}
	r, _ := hh.HashRoot()
	return r, nil
}
