// Package corpus contains generated SSZ types for fuzz testing.
//
// Types in this package are generated by the generate command and should not be
// edited manually. Run `go run ./fuzz/cmd/generate` to regenerate.
package corpus

// TypeEntry represents a generated SSZ type available for fuzz testing.
type TypeEntry struct {
	Name     string
	New      func() any
	Extended bool
}

// Registry holds all generated type entries. Populated by registry_gen.go.
var Registry []TypeEntry
