// Copyright (c) 2025 pk910
// SPDX-License-Identifier: Apache-2.0
// This file is part of the dynamic-ssz library.

package ssztypes

import (
	"math/big"
	"reflect"
	"runtime"
	"strings"

	"github.com/pk910/dynamic-ssz/sszutils"
)

var (
	byteType   = reflect.TypeOf(byte(0))
	bigIntType = reflect.TypeOf(big.Int{})
)

// Each delegate method is probed through its own interface, so a type is
// delegated to for the operations it can serve rather than for a whole family.
var sszValueMarshalerType = reflect.TypeOf((*sszutils.FastsszValueMarshaler)(nil)).Elem()
var sszBufferMarshalerType = reflect.TypeOf((*sszutils.FastsszBufferMarshaler)(nil)).Elem()
var sszSizerType = reflect.TypeOf((*sszutils.FastsszSizer)(nil)).Elem()
var sszUnmarshalerType = reflect.TypeOf((*sszutils.FastsszUnmarshaler)(nil)).Elem()
var sszHashRootType = reflect.TypeOf((*sszutils.FastsszHashRoot)(nil)).Elem()
var hashWalkerType = reflect.TypeOf((*sszutils.HashWalker)(nil)).Elem()
var dynamicMarshalerType = reflect.TypeOf((*sszutils.DynamicMarshaler)(nil)).Elem()
var dynamicUnmarshalerType = reflect.TypeOf((*sszutils.DynamicUnmarshaler)(nil)).Elem()
var dynamicEncoderType = reflect.TypeOf((*sszutils.DynamicEncoder)(nil)).Elem()
var dynamicDecoderType = reflect.TypeOf((*sszutils.DynamicDecoder)(nil)).Elem()
var dynamicSizerType = reflect.TypeOf((*sszutils.DynamicSizer)(nil)).Elem()
var dynamicHashRootType = reflect.TypeOf((*sszutils.DynamicHashRoot)(nil)).Elem()

// View-based dynamic interface types for fork-dependent SSZ schemas
var dynamicViewMarshalerType = reflect.TypeOf((*sszutils.DynamicViewMarshaler)(nil)).Elem()
var dynamicViewUnmarshalerType = reflect.TypeOf((*sszutils.DynamicViewUnmarshaler)(nil)).Elem()
var dynamicViewEncoderType = reflect.TypeOf((*sszutils.DynamicViewEncoder)(nil)).Elem()
var dynamicViewDecoderType = reflect.TypeOf((*sszutils.DynamicViewDecoder)(nil)).Elem()
var dynamicViewSizerType = reflect.TypeOf((*sszutils.DynamicViewSizer)(nil)).Elem()
var dynamicViewHashRootType = reflect.TypeOf((*sszutils.DynamicViewHashRoot)(nil)).Elem()

// delegationMethodNames are the methods dynssz delegates to instead of walking
// a type. A promoted one drops the outer struct's sibling fields, so its
// presence forces a container walk.
var delegationMethodNames = []string{
	"MarshalSSZDyn", "UnmarshalSSZDyn", "SizeSSZDyn", "HashTreeRootWithDyn",
	"MarshalSSZEncoder", "UnmarshalSSZDecoder",
	"MarshalSSZDynView", "UnmarshalSSZDynView", "SizeSSZDynView", "HashTreeRootWithDynView",
	"MarshalSSZEncoderView", "UnmarshalSSZDecoderView",
	"MarshalSSZTo", "UnmarshalSSZ", "SizeSSZ", "HashTreeRoot", "HashTreeRootWith",
}

// PromotedDelegationMethods returns the SSZ delegation methods a struct type
// only satisfies through a wrapper promoted from an embedded (anonymous)
// field, rather than a declaration of its own. Go promotes an embedded field's
// methods to the outer struct, so such a struct "implements" the interface
// even though the promoted method only knows how to serialize the embedded
// field — delegating through it silently drops the struct's sibling fields.
// Callers suppress delegation per interface: only the interfaces whose methods
// are promoted force the container walk, while an interface the struct
// declares itself (including a declaration shadowing an embedded method)
// keeps delegating.
//
// A declared method is a real source-level function, whereas a promoted method
// is a compiler-generated wrapper the runtime attributes to a synthetic
// "<autogenerated>" file. That file distinction (see methodIsPromotedWrapper)
// tells the two apart.
//
// The result is a pure function of the type and this sits on the per-call
// delegation hot path, so it is memoized per TypeCache. A nil map means no
// delegation method is promoted.
func (tc *TypeCache) PromotedDelegationMethods(targetType reflect.Type) map[string]bool {
	if v, ok := tc.promotedDelegation.Load(targetType); ok {
		cached, _ := v.(map[string]bool)
		return cached
	}
	result := structPromotedDelegationMethods(targetType)
	tc.promotedDelegation.Store(targetType, result)
	return result
}

func structPromotedDelegationMethods(targetType reflect.Type) map[string]bool {
	if targetType.Kind() == reflect.Pointer {
		targetType = targetType.Elem()
	}
	if targetType.Kind() != reflect.Struct {
		return nil
	}

	// Only an embedded field promotes methods; skip the per-method inspection
	// otherwise.
	if !structHasEmbeddedField(targetType) {
		return nil
	}

	var promoted map[string]bool
	ptrType := reflect.PointerTo(targetType)
	for _, name := range delegationMethodNames {
		ptrMethod, ok := ptrType.MethodByName(name)
		if !ok || !methodIsPromotedWrapper(&ptrMethod) {
			continue
		}
		// A method declared on the type with a value receiver is a real
		// declaration in the value method set, while the pointer method set
		// holds a compiler adapter for it; a promoted method is a wrapper in
		// both method sets, or absent from the value one when the embedded
		// field's method has a pointer receiver.
		if valueMethod, ok := targetType.MethodByName(name); ok && !methodIsPromotedWrapper(&valueMethod) {
			continue
		}
		if promoted == nil {
			promoted = make(map[string]bool, len(delegationMethodNames))
		}
		promoted[name] = true
	}
	return promoted
}

// structHasEmbeddedField reports whether the struct has an embedded
// (anonymous) field, the only way a method can be promoted to it.
func structHasEmbeddedField(targetType reflect.Type) bool {
	for i := 0; i < targetType.NumField(); i++ {
		if targetType.Field(i).Anonymous {
			return true
		}
	}
	return false
}

// methodIsPromotedWrapper reports whether a method is a compiler-generated
// promotion wrapper for an embedded field rather than a real declaration. Such
// wrappers are attributed to a synthetic file (conventionally
// "<autogenerated>"); any real declaration carries a source path. A method from
// a concrete pointer method set always resolves, so FuncForPC is non-nil here;
// an unresolvable location (empty path) is treated as promoted, keeping the
// safe default of a container walk rather than a data-dropping delegation.
func methodIsPromotedWrapper(method *reflect.Method) bool {
	file, _ := runtime.FuncForPC(method.Func.Pointer()).FileLine(method.Func.Pointer())
	return file == "" || strings.HasPrefix(file, "<")
}

// getFastsszCompatibility evaluates the compatibility of a given type with fastssz, determining whether the type and its nested
// structures can be efficiently encoded/decoded using fastssz's static code generation approach.
//
// Parameters:
// - targetType: The reflect.Type of the value being assessed for fastssz compatibility. This type, along with its nested
//   or referenced types, is evaluated to ensure it aligns with fastssz's requirements for static encoding and decoding.
//
// Returns:
// - The flag set naming each fastssz-style method the type provides.

func getFastsszCompatFlags(targetType reflect.Type) SszCompatFlag {
	targetPtrType := reflect.New(targetType).Type()

	var flags SszCompatFlag
	if targetPtrType.Implements(sszValueMarshalerType) {
		flags |= SszCompatFlagFastsszValueMarshaler
	}
	if targetPtrType.Implements(sszBufferMarshalerType) {
		flags |= SszCompatFlagFastsszBufferMarshaler
	}
	if targetPtrType.Implements(sszSizerType) {
		flags |= SszCompatFlagFastsszSizer
	}
	if targetPtrType.Implements(sszUnmarshalerType) {
		flags |= SszCompatFlagFastsszUnmarshaler
	}

	return flags
}

// getFastsszHashCompatibility evaluates the compatibility of a given type with fastssz's HashRoot interface, determining whether
// the type can efficiently compute its hash tree root using fastssz's static code generation approach.
//
// Parameters:
// - targetType: The reflect.Type of the value being assessed for fastssz hash compatibility. This type, along with its nested
//   or referenced types, is evaluated to ensure it aligns with fastssz's requirements for static hash tree root computation.
//
// Returns:
// - A boolean indicating whether the type is compatible with fastssz's static hash tree root computation.

func getFastsszHashCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(sszHashRootType)
}

// getHashTreeRootWithCompatibility evaluates the compatibility of a given type with fastssz's HashTreeRootWith method,
// determining whether the type can efficiently compute its hash tree root using fastssz's optimized hasher interface.
// This method uses reflection to detect the HashTreeRootWith method since actual implementations may use specific
// parameter types (ssz.HashWalker, *ssz.Hasher) rather than interface{}, ensuring compatibility across different
// fastssz implementations without requiring direct imports.
//
// Parameters:
//   - targetType: The reflect.Type of the value being assessed for fastssz HashTreeRootWith compatibility. This type
//     is evaluated to ensure it has a method with the signature pattern HashTreeRootWith(hasher) error, regardless
//     of the specific hasher parameter type used.
//
// Returns:
//   - The method if found and valid, nil otherwise. This allows caching for performance optimization.
func getHashTreeRootWithCompatibility(targetType reflect.Type) *reflect.Method {
	targetPtrType := reflect.New(targetType).Type()

	// Check if the type has a method named "HashTreeRootWith"
	method, found := targetPtrType.MethodByName("HashTreeRootWith")
	if !found {
		return nil
	}

	// Check the method signature:
	// - Should have exactly 2 parameters (receiver + hasher parameter)
	// - Should return exactly 1 value (error)
	methodType := method.Type
	if methodType.NumIn() != 2 || methodType.NumOut() != 1 {
		return nil
	}

	// Check that it returns an error
	errorType := reflect.TypeOf((*error)(nil)).Elem()
	if !methodType.Out(0).AssignableTo(errorType) {
		return nil
	}

	// The method must accept a hasher we can actually supply. At hash time dynssz
	// always passes its own hasher (as a sszutils.HashWalker). A method whose
	// parameter is an interface that our HashWalker satisfies (e.g. ssz.HashWalker)
	// is callable; the standard fastssz sszgen output declares
	// HashTreeRootWith(*ssz.Hasher) with a concrete foreign hasher type, which
	// would panic in reflect.Call. Reject the latter so the type-safe
	// HashTreeRoot() fallback is used instead.
	paramType := methodType.In(1)
	if paramType.Kind() != reflect.Interface || !hashWalkerType.Implements(paramType) {
		return nil
	}

	return &method
}

// getDynamicMarshalerCompatibility checks if a type implements the DynamicMarshaler interface
func getDynamicMarshalerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicMarshalerType)
}

// getDynamicUnmarshalerCompatibility checks if a type implements the DynamicUnmarshaler interface
func getDynamicUnmarshalerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicUnmarshalerType)
}

// getDynamicEncoderCompatibility checks if a type implements the DynamicEncoder interface
func getDynamicEncoderCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicEncoderType)
}

// getDynamicDecoderCompatibility checks if a type implements the DynamicDecoder interface
func getDynamicDecoderCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicDecoderType)
}

// getDynamicSizerCompatibility checks if a type implements the DynamicSizer interface
func getDynamicSizerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicSizerType)
}

// getDynamicHashRootCompatibility checks if a type implements the DynamicHashRoot interface
func getDynamicHashRootCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicHashRootType)
}

// getDynamicViewMarshalerCompatibility checks if a type implements the DynamicViewMarshaler interface
func getDynamicViewMarshalerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewMarshalerType)
}

// getDynamicViewUnmarshalerCompatibility checks if a type implements the DynamicViewUnmarshaler interface
func getDynamicViewUnmarshalerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewUnmarshalerType)
}

// getDynamicViewEncoderCompatibility checks if a type implements the DynamicViewEncoder interface
func getDynamicViewEncoderCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewEncoderType)
}

// getDynamicViewDecoderCompatibility checks if a type implements the DynamicViewDecoder interface
func getDynamicViewDecoderCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewDecoderType)
}

// getDynamicViewSizerCompatibility checks if a type implements the DynamicViewSizer interface
func getDynamicViewSizerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewSizerType)
}

// getDynamicViewHashRootCompatibility checks if a type implements the DynamicViewHashRoot interface
func getDynamicViewHashRootCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewHashRootType)
}
