// Copyright (c) 2025 pk910
// SPDX-License-Identifier: Apache-2.0
// This file is part of the dynamic-ssz library.

package ssztypes

import (
	"reflect"
	"runtime"
	"strings"

	"github.com/pk910/dynamic-ssz/sszutils"
)

var byteType = reflect.TypeOf(byte(0))
var sszMarshalerType = reflect.TypeOf((*sszutils.FastsszMarshaler)(nil)).Elem()
var sszUnmarshalerType = reflect.TypeOf((*sszutils.FastsszUnmarshaler)(nil)).Elem()
var sszHashRootType = reflect.TypeOf((*sszutils.FastsszHashRoot)(nil)).Elem()
var hashWalkerType = reflect.TypeOf((*sszutils.HashWalker)(nil)).Elem()
var dynamicMarshalerType = reflect.TypeOf((*sszutils.DynamicMarshaler)(nil)).Elem()
var dynamicUnmarshalerType = reflect.TypeOf((*sszutils.DynamicUnmarshaler)(nil)).Elem()
var dynamicEncoderType = reflect.TypeOf((*sszutils.DynamicEncoder)(nil)).Elem()
var dynamicDecoderType = reflect.TypeOf((*sszutils.DynamicDecoder)(nil)).Elem()
var dynamicSizerType = reflect.TypeOf((*sszutils.DynamicSizer)(nil)).Elem()
var dynamicHashRootType = reflect.TypeOf((*sszutils.DynamicHashRoot)(nil)).Elem()

// View-based dynamic interface types for fork-dependent SSZ schemas
var dynamicViewMarshalerType = reflect.TypeOf((*sszutils.DynamicViewMarshaler)(nil)).Elem()
var dynamicViewUnmarshalerType = reflect.TypeOf((*sszutils.DynamicViewUnmarshaler)(nil)).Elem()
var dynamicViewEncoderType = reflect.TypeOf((*sszutils.DynamicViewEncoder)(nil)).Elem()
var dynamicViewDecoderType = reflect.TypeOf((*sszutils.DynamicViewDecoder)(nil)).Elem()
var dynamicViewSizerType = reflect.TypeOf((*sszutils.DynamicViewSizer)(nil)).Elem()
var dynamicViewHashRootType = reflect.TypeOf((*sszutils.DynamicViewHashRoot)(nil)).Elem()

// delegationInterfaces lists the SSZ delegation interfaces whose presence makes
// dynssz serialize a type through its own methods instead of walking it. Used
// as a cheap structural pre-check in StructInheritsPromotedDelegation.
var delegationInterfaces = []reflect.Type{
	dynamicMarshalerType, dynamicUnmarshalerType,
	dynamicEncoderType, dynamicDecoderType,
	dynamicSizerType, dynamicHashRootType,
	sszMarshalerType, sszUnmarshalerType, sszHashRootType,
}

// delegationMethodNames are the methods behind delegationInterfaces. A promoted
// one drops the outer struct's sibling fields, so its presence forces a
// container walk.
var delegationMethodNames = []string{
	"MarshalSSZDyn", "UnmarshalSSZDyn", "SizeSSZDyn", "HashTreeRootWithDyn",
	"MarshalSSZEncoder", "UnmarshalSSZDecoder",
	"MarshalSSZTo", "UnmarshalSSZ", "SizeSSZ", "HashTreeRoot", "HashTreeRootWith",
}

// InheritsPromotedDelegation reports whether a struct type exposes an SSZ
// delegation method that is promoted from an embedded (anonymous) field rather
// than declared on the struct itself. Go promotes an embedded field's methods
// to the outer struct, so such a struct "implements" the interface even though
// the promoted method only knows how to serialize the embedded field —
// delegating to it silently drops the struct's sibling fields. When this is
// true the type must be walked as a container; the embedded field still
// delegates correctly as one of the walked fields.
//
// A method the struct declares itself (including one that shadows an embedded
// method) is a real source-level function, whereas a promoted method is a
// compiler-generated wrapper the runtime attributes to a synthetic
// "<autogenerated>" file. That file distinction (see methodIsPromotedWrapper)
// tells the two apart, so a struct that both embeds a delegating type and
// declares its own methods still delegates through its own declarations.
//
// The result is a pure function of the type and this sits on the per-call
// delegation hot path, so it is memoized per TypeCache.
func (tc *TypeCache) InheritsPromotedDelegation(targetType reflect.Type) bool {
	if v, ok := tc.promotedDelegation.Load(targetType); ok {
		cached, _ := v.(bool)
		return cached
	}
	result := structInheritsPromotedDelegation(targetType)
	tc.promotedDelegation.Store(targetType, result)
	return result
}

func structInheritsPromotedDelegation(targetType reflect.Type) bool {
	if targetType.Kind() == reflect.Pointer {
		targetType = targetType.Elem()
	}
	if targetType.Kind() != reflect.Struct {
		return false
	}

	// Promotion is only possible when an embedded field provides a delegation
	// interface; skip the per-method wrapper inspection otherwise.
	if !structHasDelegatingEmbeddedField(targetType) {
		return false
	}

	ptrType := reflect.PointerTo(targetType)
	for _, name := range delegationMethodNames {
		if method, ok := ptrType.MethodByName(name); ok && methodIsPromotedWrapper(&method) {
			return true
		}
	}
	return false
}

// structHasDelegatingEmbeddedField reports whether any embedded (anonymous)
// field of the struct provides an SSZ delegation interface, i.e. whether a
// delegation method could be promoted to the struct.
func structHasDelegatingEmbeddedField(targetType reflect.Type) bool {
	for i := 0; i < targetType.NumField(); i++ {
		field := targetType.Field(i)
		if !field.Anonymous {
			continue
		}
		embeddedPtr := field.Type
		if embeddedPtr.Kind() != reflect.Pointer {
			embeddedPtr = reflect.PointerTo(embeddedPtr)
		}
		for _, iface := range delegationInterfaces {
			if embeddedPtr.Implements(iface) {
				return true
			}
		}
	}
	return false
}

// methodIsPromotedWrapper reports whether a method is a compiler-generated
// promotion wrapper for an embedded field rather than a real declaration. Such
// wrappers are attributed to a synthetic file (conventionally
// "<autogenerated>"); any real declaration carries a source path. Treating an
// unresolvable location as promoted keeps the safe default — a container walk
// rather than a data-dropping delegation.
func methodIsPromotedWrapper(method *reflect.Method) bool {
	fn := runtime.FuncForPC(method.Func.Pointer())
	if fn == nil {
		return true
	}
	file, _ := fn.FileLine(method.Func.Pointer())
	return file == "" || strings.HasPrefix(file, "<")
}

// getFastsszCompatibility evaluates the compatibility of a given type with fastssz, determining whether the type and its nested
// structures can be efficiently encoded/decoded using fastssz's static code generation approach.
//
// Parameters:
// - targetType: The reflect.Type of the value being assessed for fastssz compatibility. This type, along with its nested
//   or referenced types, is evaluated to ensure it aligns with fastssz's requirements for static encoding and decoding.
//
// Returns:
// - A boolean indicating whether the type is compatible with fastssz's static encoding and decoding.

func getFastsszConvertCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(sszMarshalerType) && targetPtrType.Implements(sszUnmarshalerType)
}

// getFastsszHashCompatibility evaluates the compatibility of a given type with fastssz's HashRoot interface, determining whether
// the type can efficiently compute its hash tree root using fastssz's static code generation approach.
//
// Parameters:
// - targetType: The reflect.Type of the value being assessed for fastssz hash compatibility. This type, along with its nested
//   or referenced types, is evaluated to ensure it aligns with fastssz's requirements for static hash tree root computation.
//
// Returns:
// - A boolean indicating whether the type is compatible with fastssz's static hash tree root computation.

func getFastsszHashCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(sszHashRootType)
}

// getHashTreeRootWithCompatibility evaluates the compatibility of a given type with fastssz's HashTreeRootWith method,
// determining whether the type can efficiently compute its hash tree root using fastssz's optimized hasher interface.
// This method uses reflection to detect the HashTreeRootWith method since actual implementations may use specific
// parameter types (ssz.HashWalker, *ssz.Hasher) rather than interface{}, ensuring compatibility across different
// fastssz implementations without requiring direct imports.
//
// Parameters:
//   - targetType: The reflect.Type of the value being assessed for fastssz HashTreeRootWith compatibility. This type
//     is evaluated to ensure it has a method with the signature pattern HashTreeRootWith(hasher) error, regardless
//     of the specific hasher parameter type used.
//
// Returns:
//   - The method if found and valid, nil otherwise. This allows caching for performance optimization.
func getHashTreeRootWithCompatibility(targetType reflect.Type) *reflect.Method {
	targetPtrType := reflect.New(targetType).Type()

	// Check if the type has a method named "HashTreeRootWith"
	method, found := targetPtrType.MethodByName("HashTreeRootWith")
	if !found {
		return nil
	}

	// Check the method signature:
	// - Should have exactly 2 parameters (receiver + hasher parameter)
	// - Should return exactly 1 value (error)
	methodType := method.Type
	if methodType.NumIn() != 2 || methodType.NumOut() != 1 {
		return nil
	}

	// Check that it returns an error
	errorType := reflect.TypeOf((*error)(nil)).Elem()
	if !methodType.Out(0).AssignableTo(errorType) {
		return nil
	}

	// The method must accept a hasher we can actually supply. At hash time dynssz
	// always passes its own hasher (as a sszutils.HashWalker). A method whose
	// parameter is an interface that our HashWalker satisfies (e.g. ssz.HashWalker)
	// is callable; the standard fastssz sszgen output declares
	// HashTreeRootWith(*ssz.Hasher) with a concrete foreign hasher type, which
	// would panic in reflect.Call. Reject the latter so the type-safe
	// HashTreeRoot() fallback is used instead.
	paramType := methodType.In(1)
	if paramType.Kind() != reflect.Interface || !hashWalkerType.Implements(paramType) {
		return nil
	}

	return &method
}

// getDynamicMarshalerCompatibility checks if a type implements the DynamicMarshaler interface
func getDynamicMarshalerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicMarshalerType)
}

// getDynamicUnmarshalerCompatibility checks if a type implements the DynamicUnmarshaler interface
func getDynamicUnmarshalerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicUnmarshalerType)
}

// getDynamicEncoderCompatibility checks if a type implements the DynamicEncoder interface
func getDynamicEncoderCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicEncoderType)
}

// getDynamicDecoderCompatibility checks if a type implements the DynamicDecoder interface
func getDynamicDecoderCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicDecoderType)
}

// getDynamicSizerCompatibility checks if a type implements the DynamicSizer interface
func getDynamicSizerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicSizerType)
}

// getDynamicHashRootCompatibility checks if a type implements the DynamicHashRoot interface
func getDynamicHashRootCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicHashRootType)
}

// getDynamicViewMarshalerCompatibility checks if a type implements the DynamicViewMarshaler interface
func getDynamicViewMarshalerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewMarshalerType)
}

// getDynamicViewUnmarshalerCompatibility checks if a type implements the DynamicViewUnmarshaler interface
func getDynamicViewUnmarshalerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewUnmarshalerType)
}

// getDynamicViewEncoderCompatibility checks if a type implements the DynamicViewEncoder interface
func getDynamicViewEncoderCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewEncoderType)
}

// getDynamicViewDecoderCompatibility checks if a type implements the DynamicViewDecoder interface
func getDynamicViewDecoderCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewDecoderType)
}

// getDynamicViewSizerCompatibility checks if a type implements the DynamicViewSizer interface
func getDynamicViewSizerCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewSizerType)
}

// getDynamicViewHashRootCompatibility checks if a type implements the DynamicViewHashRoot interface
func getDynamicViewHashRootCompatibility(targetType reflect.Type) bool {
	targetPtrType := reflect.New(targetType).Type()
	return targetPtrType.Implements(dynamicViewHashRootType)
}
