//go:build ignore

// Command gen writes the embedding matrix: for each of the six fastssz-style
// methods, the outer type either declares it, promotes it from an embedded
// type, or does not have it at all.
//
// Every declared method is correct for the outer value and every promoted one
// is correct for the embedded value, so the right answer is the same for all
// 3^6 shapes -- the outer value -- and a single expectation covers the matrix.
// A shape that reaches a promoted method answers for the embedded value instead
// and is caught.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

// The methods, in the order their state is encoded in a type's name.
var methods = []string{"MarshalSSZ", "MarshalSSZTo", "SizeSSZ", "UnmarshalSSZ", "HashTreeRoot", "HashTreeRootWith"}

const (
	absent = iota
	declared
	promoted
)

// inner answers for one uint64, the value it holds.
func innerMethod(name, recv string) string {
	switch name {
	case "MarshalSSZ":
		return fmt.Sprintf("func (t *%s) MarshalSSZ() ([]byte, error) { return binary.LittleEndian.AppendUint64(nil, t.V), nil }", recv)
	case "MarshalSSZTo":
		return fmt.Sprintf("func (t *%s) MarshalSSZTo(dst []byte) ([]byte, error) { return binary.LittleEndian.AppendUint64(dst, t.V), nil }", recv)
	case "SizeSSZ":
		return fmt.Sprintf("func (t *%s) SizeSSZ() int { return 8 }", recv)
	case "UnmarshalSSZ":
		return fmt.Sprintf("func (t *%s) UnmarshalSSZ(b []byte) error {\n\tif len(b) != 8 {\n\t\treturn errors.New(\"inner: wrong length\")\n\t}\n\tt.V = binary.LittleEndian.Uint64(b)\n\treturn nil\n}", recv)
	case "HashTreeRoot":
		return fmt.Sprintf("func (t *%s) HashTreeRoot() ([32]byte, error) {\n\tvar r [32]byte\n\tbinary.LittleEndian.PutUint64(r[:8], t.V)\n\treturn r, nil\n}", recv)
	case "HashTreeRootWith":
		return fmt.Sprintf("func (t *%s) HashTreeRootWith(hw sszutils.HashWalker) error {\n\tidx := hw.Index()\n\thw.PutUint64(t.V)\n\thw.Merkleize(idx)\n\treturn nil\n}", recv)
	}
	panic("unknown method " + name)
}

// outer answers for both uint64s, which is what the whole value encodes to.
func outerMethod(name, recv string) string {
	switch name {
	case "MarshalSSZ":
		return fmt.Sprintf("func (t *%s) MarshalSSZ() ([]byte, error) {\n\tb := binary.LittleEndian.AppendUint64(nil, t.V)\n\treturn binary.LittleEndian.AppendUint64(b, t.W), nil\n}", recv)
	case "MarshalSSZTo":
		return fmt.Sprintf("func (t *%s) MarshalSSZTo(dst []byte) ([]byte, error) {\n\tdst = binary.LittleEndian.AppendUint64(dst, t.V)\n\treturn binary.LittleEndian.AppendUint64(dst, t.W), nil\n}", recv)
	case "SizeSSZ":
		return fmt.Sprintf("func (t *%s) SizeSSZ() int { return 16 }", recv)
	case "UnmarshalSSZ":
		return fmt.Sprintf("func (t *%s) UnmarshalSSZ(b []byte) error {\n\tif len(b) != 16 {\n\t\treturn errors.New(\"outer: wrong length\")\n\t}\n\tt.V = binary.LittleEndian.Uint64(b[:8])\n\tt.W = binary.LittleEndian.Uint64(b[8:])\n\treturn nil\n}", recv)
	case "HashTreeRoot":
		return fmt.Sprintf("func (t *%s) HashTreeRoot() ([32]byte, error) { return PairRoot(t.V, t.W), nil }", recv)
	case "HashTreeRootWith":
		return fmt.Sprintf("func (t *%s) HashTreeRootWith(hw sszutils.HashWalker) error {\n\tidx := hw.Index()\n\thw.PutUint64(t.V)\n\thw.PutUint64(t.W)\n\thw.Merkleize(idx)\n\treturn nil\n}", recv)
	}
	panic("unknown method " + name)
}

func main() {
	var b bytes.Buffer
	fmt.Fprint(&b, `// Code generated by gen.go. DO NOT EDIT.

package promomatrix

import (
	"crypto/sha256"
	"encoding/binary"
	"errors"

	"github.com/pk910/dynamic-ssz/sszutils"
)

// PairRoot is the root of a container of two uint64s: each value right-padded
// into its own chunk, the two chunks hashed together. It is computed here
// rather than asked of the library, so the matrix is not checking the library
// against itself.
func PairRoot(v, w uint64) [32]byte {
	var buf [64]byte
	binary.LittleEndian.PutUint64(buf[0:8], v)
	binary.LittleEndian.PutUint64(buf[32:40], w)
	return sha256.Sum256(buf[:])
}
`)

	// One inner type per subset of methods that some outer type promotes.
	for mask := 0; mask < 1<<len(methods); mask++ {
		name := fmt.Sprintf("Inner%02d", mask)
		fmt.Fprintf(&b, "\ntype %s struct{ V uint64 }\n", name)
		for i, m := range methods {
			if mask&(1<<i) != 0 {
				fmt.Fprintf(&b, "%s\n", innerMethod(m, name))
			}
		}
	}

	var names []string
	var newCases, emptyCases, getCases strings.Builder
	var state [6]int
	var rec func(int)
	rec = func(pos int) {
		if pos == len(methods) {
			var digits, mask strings.Builder
			for i, s := range state {
				fmt.Fprintf(&digits, "%d", s)
				if s == promoted {
					mask.WriteString("1")
				} else {
					mask.WriteString("0")
				}
				_ = i
			}
			// the inner carries exactly the promoted methods
			innerMask := 0
			for i, s := range state {
				if s == promoted {
					innerMask |= 1 << i
				}
			}
			name := "T" + digits.String()
			names = append(names, name)
			fmt.Fprintf(&b, "\ntype %s struct {\n\tInner%02d\n\tW uint64\n}\n", name, innerMask)
			for i, m := range methods {
				if state[i] == declared {
					fmt.Fprintf(&b, "%s\n", outerMethod(m, name))
				}
			}
			fmt.Fprintf(&newCases, "\tcase %q:\n\t\tt := &%s{W: w}\n\t\tt.V = v\n\t\treturn t\n", name, name)
			fmt.Fprintf(&emptyCases, "\tcase %q:\n\t\treturn new(%s)\n", name, name)
			fmt.Fprintf(&getCases, "\tcase *%s:\n\t\treturn t.V, t.W\n", name)
			return
		}
		for s := absent; s <= promoted; s++ {
			state[pos] = s
			rec(pos + 1)
		}
	}
	rec(0)

	fmt.Fprintf(&b, "\n// Names lists every shape, its digits giving each method's state:\n// 0 absent, 1 declared on the outer type, 2 promoted from the embedded one.\nvar Names = []string{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q,\n", n)
	}
	fmt.Fprint(&b, "}\n")

	fmt.Fprintf(&b, "\n// New builds the named shape holding v and w.\nfunc New(name string, v, w uint64) any {\n\tswitch name {\n%s\t}\n\tpanic(\"unknown shape \" + name)\n}\n", newCases.String())
	fmt.Fprintf(&b, "\n// Empty builds the named shape zeroed, to decode into.\nfunc Empty(name string) any {\n\tswitch name {\n%s\t}\n\tpanic(\"unknown shape \" + name)\n}\n", emptyCases.String())
	fmt.Fprintf(&b, "\n// Get reads the two values back out of any shape.\nfunc Get(value any) (uint64, uint64) {\n\tswitch t := value.(type) {\n%s\t}\n\tpanic(\"unknown shape\")\n}\n", getCases.String())

	src, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "format:", err)
		os.Exit(1)
	}
	if err := os.WriteFile("gen_matrix.go", src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// The driver is generated alongside the shapes: it names symbols that only
	// exist once they are, so committing it would leave the tree unbuildable
	// before the first generate.
	test, err := format.Source([]byte(driver))
	if err != nil {
		fmt.Fprintln(os.Stderr, "format driver:", err)
		os.Exit(1)
	}
	if err := os.WriteFile("gen_matrix_test.go", test, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote gen_matrix.go and gen_matrix_test.go: %d shapes\n", len(names))
}

const driver = `// Code generated by gen.go. DO NOT EDIT.

package promomatrix

import (
	"bytes"
	"encoding/binary"
	"testing"

	dynssz "github.com/pk910/dynamic-ssz"
)

// Every shape holds the same two values and must answer for both of them on
// every operation, whichever of its methods are declared, promoted or absent.
// A shape whose answer covers only the embedded value has reached a promoted
// method: correct for the value it was written for, wrong for this one.
//
// Both engines are driven. Delegating, a declared method answers and a promoted
// one must not be reached. Under no-delegation every method is ignored and the
// value is walked, which reaches the same bytes and the same root by a wholly
// different route -- so the two columns together say the delegation decision
// did not change the answer, not merely that it was self-consistent.
func TestEmbeddingMatrix(t *testing.T) {
	const v = uint64(0x1122334455667788)
	const w = uint64(0x99aabbccddeeff00)

	want := binary.LittleEndian.AppendUint64(nil, v)
	want = binary.LittleEndian.AppendUint64(want, w)
	wantRoot := PairRoot(v, w)
	prefix := []byte{0xde, 0xad, 0xbe, 0xef}

	engines := []struct {
		name string
		ds   *dynssz.DynSsz
	}{
		{"delegating", dynssz.NewDynSsz(nil)},
		{"reflection", dynssz.NewDynSsz(nil, dynssz.WithNoFastSsz(), dynssz.WithNoDelegation())},
	}

	for _, engine := range engines {
		t.Run(engine.name, func(t *testing.T) {
			ds := engine.ds
			for _, name := range Names {
				t.Run(name, func(t *testing.T) {
					value := New(name, v, w)

					if got, err := ds.MarshalSSZ(value); err != nil || !bytes.Equal(got, want) {
						t.Errorf("MarshalSSZ = %x, %v; want %x", got, err, want)
					}

					// Appends after what the caller already holds.
					wantAppended := append(append([]byte(nil), prefix...), want...)
					if got, err := ds.MarshalSSZTo(value, append([]byte(nil), prefix...)); err != nil || !bytes.Equal(got, wantAppended) {
						t.Errorf("MarshalSSZTo = %x, %v; want %x", got, err, wantAppended)
					}

					var stream bytes.Buffer
					if err := ds.MarshalSSZWriter(value, &stream); err != nil || !bytes.Equal(stream.Bytes(), want) {
						t.Errorf("MarshalSSZWriter = %x, %v; want %x", stream.Bytes(), err, want)
					}

					if got, err := ds.SizeSSZ(value); err != nil || got != len(want) {
						t.Errorf("SizeSSZ = %d, %v; want %d", got, err, len(want))
					}

					if got, err := ds.HashTreeRoot(value); err != nil || got != wantRoot {
						t.Errorf("HashTreeRoot = %x, %v; want %x", got, err, wantRoot)
					}

					// GetTree drives the tree walker rather than the hasher, so a
					// shape that reaches a promoted method on one and not the
					// other shows up as a tree disagreeing with the root.
					if tree, err := ds.GetTree(value); err != nil {
						t.Errorf("GetTree: %v", err)
					} else if got := tree.Hash(); !bytes.Equal(got, wantRoot[:]) {
						t.Errorf("GetTree root = %x; want %x", got, wantRoot)
					}

					into := Empty(name)
					if err := ds.UnmarshalSSZ(into, want); err != nil {
						t.Errorf("UnmarshalSSZ: %v", err)
					} else if gv, gw := Get(into); gv != v || gw != w {
						t.Errorf("UnmarshalSSZ round trip = %x, %x; want %x, %x", gv, gw, v, w)
					}

					intoReader := Empty(name)
					if err := ds.UnmarshalSSZReader(intoReader, bytes.NewReader(want), len(want)); err != nil {
						t.Errorf("UnmarshalSSZReader: %v", err)
					} else if gv, gw := Get(intoReader); gv != v || gw != w {
						t.Errorf("UnmarshalSSZReader round trip = %x, %x; want %x, %x", gv, gw, v, w)
					}
				})
			}
		})
	}
}
`
