// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: ce77e43147f4817885d6b314aec6e2684321d8e42ae87304fe04fe239836ce0e
// Version: v1.4.0-pre.1 (https://github.com/pk910/dynamic-ssz)
package main

import (
	"encoding/binary"
	"math"

	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[Validator](`ssz-static:"true"`)
var _ = sszutils.Annotate[CachedValidator](`ssz-static:"true"`)
var _ = sszutils.Annotate[CachedRegistry](`ssz-static:"false"`)
var _ = sszutils.Annotate[PlainRegistry](`ssz-static:"false"`)

// MarshalSSZTo marshals the *Validator to SSZ-encoded bytes, appending to the provided buffer.
func (t *Validator) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(Validator)
	}
	{ // Static Field #0 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Static Field #1 'WithdrawalCredentials'
		dst = append(dst, t.WithdrawalCredentials[:32]...)
	}
	{ // Static Field #2 'EffectiveBalance'
		dst = binary.LittleEndian.AppendUint64(dst, t.EffectiveBalance)
	}
	{ // Static Field #3 'Slashed'
		dst = sszutils.MarshalBool(dst, t.Slashed)
	}
	{ // Static Field #4 'ActivationEligibilityEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, t.ActivationEligibilityEpoch)
	}
	{ // Static Field #5 'ActivationEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, t.ActivationEpoch)
	}
	{ // Static Field #6 'ExitEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, t.ExitEpoch)
	}
	{ // Static Field #7 'WithdrawableEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, t.WithdrawableEpoch)
	}
	return dst, nil
}

// MarshalSSZDyn marshals the *Validator to SSZ-encoded bytes using dynamic specifications.
func (t *Validator) MarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	return t.MarshalSSZTo(buf)
}

// UnmarshalSSZ unmarshals the *Validator from SSZ-encoded bytes.
func (t *Validator) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if 121 != buflen {
		if 121 > buflen {
			return sszutils.ErrFixedFieldsEOFFn(buflen, 121)
		}
		return sszutils.ErrTrailingDataFn(buflen - 121)
	}
	{ // Field #0 'Pubkey' (static)
		buf := buf[0:48]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #1 'WithdrawalCredentials' (static)
		buf := buf[48:80]
		copy(t.WithdrawalCredentials[:], buf)
	}
	{ // Field #2 'EffectiveBalance' (static)
		buf := buf[80:88]
		t.EffectiveBalance = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #3 'Slashed' (static)
		buf := buf[88:89]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidBoolValueFn()
		}
		t.Slashed = buf[0] == 1
	}
	{ // Field #4 'ActivationEligibilityEpoch' (static)
		buf := buf[89:97]
		t.ActivationEligibilityEpoch = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #5 'ActivationEpoch' (static)
		buf := buf[97:105]
		t.ActivationEpoch = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #6 'ExitEpoch' (static)
		buf := buf[105:113]
		t.ExitEpoch = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'WithdrawableEpoch' (static)
		buf := buf[113:121]
		t.WithdrawableEpoch = binary.LittleEndian.Uint64(buf)
	}
	return nil
}

// UnmarshalSSZDyn unmarshals the *Validator from SSZ-encoded bytes using dynamic specifications.
func (t *Validator) UnmarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (err error) {
	return t.UnmarshalSSZ(buf)
}

// SizeSSZ returns the SSZ encoded size of the *Validator.
func (t *Validator) SizeSSZ() (size int) {
	return 121
}

// SizeSSZDyn returns the SSZ encoded size of the *Validator using dynamic specifications.
func (t *Validator) SizeSSZDyn(_ sszutils.DynamicSpecs) (size int) {
	return t.SizeSSZ()
}

// HashTreeRoot computes the SSZ hash tree root of the *Validator.
func (t *Validator) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *Validator using the given hash walker.
func (t *Validator) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(Validator)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	{ // Field #1 'WithdrawalCredentials'
		hh.PutBytes(t.WithdrawalCredentials[:32])
	}
	{ // Field #2 'EffectiveBalance'
		hh.PutUint64(t.EffectiveBalance)
	}
	{ // Field #3 'Slashed'
		hh.PutBool(t.Slashed)
	}
	{ // Field #4 'ActivationEligibilityEpoch'
		hh.PutUint64(t.ActivationEligibilityEpoch)
	}
	{ // Field #5 'ActivationEpoch'
		hh.PutUint64(t.ActivationEpoch)
	}
	{ // Field #6 'ExitEpoch'
		hh.PutUint64(t.ExitEpoch)
	}
	{ // Field #7 'WithdrawableEpoch'
		hh.PutUint64(t.WithdrawableEpoch)
	}
	hh.Merkleize(idx)
	return nil
}

// HashTreeRootDyn computes the SSZ hash tree root of the *Validator using dynamic specifications.
func (t *Validator) HashTreeRootDyn(ds sszutils.DynamicSpecs) (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWithDyn(ds, hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWithDyn computes the SSZ hash tree root of the *Validator using dynamic specifications and the given hash walker.
func (t *Validator) HashTreeRootWithDyn(_ sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	return t.HashTreeRootWith(hh)
}

// MarshalSSZTo marshals the *CachedValidator to SSZ-encoded bytes, appending to the provided buffer.
func (t *CachedValidator) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(CachedValidator)
	}
	{
		t := &t.Data
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	return dst, nil
}

// MarshalSSZDyn marshals the *CachedValidator to SSZ-encoded bytes using dynamic specifications.
func (t *CachedValidator) MarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	return t.MarshalSSZTo(buf)
}

// UnmarshalSSZ unmarshals the *CachedValidator from SSZ-encoded bytes.
func (t *CachedValidator) UnmarshalSSZ(buf []byte) (err error) {
	if err = t.Data.UnmarshalSSZ(buf); err != nil {
		return err
	}
	return nil
}

// UnmarshalSSZDyn unmarshals the *CachedValidator from SSZ-encoded bytes using dynamic specifications.
func (t *CachedValidator) UnmarshalSSZDyn(_ sszutils.DynamicSpecs, buf []byte) (err error) {
	return t.UnmarshalSSZ(buf)
}

// SizeSSZDyn returns the SSZ encoded size of the *CachedValidator using dynamic specifications.
func (t *CachedValidator) SizeSSZDyn(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(CachedValidator)
	}
	size += t.Data.SizeSSZDyn(ds)
	return size
}

// MarshalSSZDyn marshals the *CachedRegistry to SSZ-encoded bytes using dynamic specifications.
func (t *CachedRegistry) MarshalSSZDyn(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "VALIDATOR_REGISTRY_LIMIT", 1099511627776)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(CachedRegistry)
	}
	dstlen := len(dst)
	// Offset Field #0 'Validators'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Validators'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Validators
		vlen := len(t)
		if uint64(vlen) > expr0 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Validators")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(CachedValidator)
			}
			if dst, err = t.MarshalSSZDyn(ds, dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZDyn unmarshals the *CachedRegistry from SSZ-encoded bytes using dynamic specifications.
func (t *CachedRegistry) UnmarshalSSZDyn(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "VALIDATOR_REGISTRY_LIMIT", 1099511627776)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'Validators' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "Validators:o")
	}
	{ // Field #0 'Validators' (dynamic)
		buf := buf[offset0:]
		val1 := t.Validators
		itemCount := len(buf) / 121
		if len(buf)%121 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 121), "Validators")
		}
		if uint64(max(itemCount, 0)) > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr0), "Validators")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(CachedValidator)
			}
			buf := buf[121*idx1 : 121*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZDyn(ds, buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
		t.Validators = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *CachedRegistry.
func (t *CachedRegistry) SizeSSZ() (size int) {
	if t == nil {
		t = new(CachedRegistry)
	}
	// Field #0 'Validators' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'Validators'
		size += len(t.Validators) * 121
	}
	return size
}

// SizeSSZDyn returns the SSZ encoded size of the *CachedRegistry using dynamic specifications.
func (t *CachedRegistry) SizeSSZDyn(_ sszutils.DynamicSpecs) (size int) {
	return t.SizeSSZ()
}

// HashTreeRootDyn computes the SSZ hash tree root of the *CachedRegistry using dynamic specifications.
func (t *CachedRegistry) HashTreeRootDyn(ds sszutils.DynamicSpecs) (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWithDyn(ds, hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWithDyn computes the SSZ hash tree root of the *CachedRegistry using dynamic specifications and the given hash walker.
func (t *CachedRegistry) HashTreeRootWithDyn(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "VALIDATOR_REGISTRY_LIMIT", 1099511627776)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(CachedRegistry)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Validators'
		t := t.Validators
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Validators")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(CachedValidator)
			}
			if err := t.HashTreeRootWithDyn(ds, hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

// MarshalSSZDyn marshals the *PlainRegistry to SSZ-encoded bytes using dynamic specifications.
func (t *PlainRegistry) MarshalSSZDyn(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "VALIDATOR_REGISTRY_LIMIT", 1099511627776)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(PlainRegistry)
	}
	dstlen := len(dst)
	// Offset Field #0 'Validators'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Validators'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Validators
		vlen := len(t)
		if uint64(vlen) > expr0 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Validators")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(Validator)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZDyn unmarshals the *PlainRegistry from SSZ-encoded bytes using dynamic specifications.
func (t *PlainRegistry) UnmarshalSSZDyn(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "VALIDATOR_REGISTRY_LIMIT", 1099511627776)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'Validators' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "Validators:o")
	}
	{ // Field #0 'Validators' (dynamic)
		buf := buf[offset0:]
		val1 := t.Validators
		itemCount := len(buf) / 121
		if len(buf)%121 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 121), "Validators")
		}
		if uint64(max(itemCount, 0)) > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr0), "Validators")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(Validator)
			}
			buf := buf[121*idx1 : 121*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
		t.Validators = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *PlainRegistry.
func (t *PlainRegistry) SizeSSZ() (size int) {
	if t == nil {
		t = new(PlainRegistry)
	}
	// Field #0 'Validators' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'Validators'
		size += len(t.Validators) * 121
	}
	return size
}

// SizeSSZDyn returns the SSZ encoded size of the *PlainRegistry using dynamic specifications.
func (t *PlainRegistry) SizeSSZDyn(_ sszutils.DynamicSpecs) (size int) {
	return t.SizeSSZ()
}

// HashTreeRootDyn computes the SSZ hash tree root of the *PlainRegistry using dynamic specifications.
func (t *PlainRegistry) HashTreeRootDyn(ds sszutils.DynamicSpecs) (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWithDyn(ds, hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWithDyn computes the SSZ hash tree root of the *PlainRegistry using dynamic specifications and the given hash walker.
func (t *PlainRegistry) HashTreeRootWithDyn(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "VALIDATOR_REGISTRY_LIMIT", 1099511627776)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(PlainRegistry)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Validators'
		t := t.Validators
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Validators")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(Validator)
			}
			if err := t.HashTreeRootWithDyn(ds, hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
