name: Examples

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        example: [basic, versioned-blocks, custom-types]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-examples-${{ hashFiles('**/go.sum') }}
          
    - name: Download main module dependencies
      run: go mod download
      
    - name: Build and run example
      run: |
        cd examples/${{ matrix.example }}
        go mod download
        go run .
